version: "3.9"

services:
  mss_todo_app:
    container_name: mss_todo_app
    #    build: .
    #    image: spring_boot_crud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_db:5432/todo_app
      - spring.datasource.username=postgres
      - spring.datasource.password=12345
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: todo_app
    volumes:
      - /home/tanver/Documents/Software/Backup-DB/postgres:/var/lib/postgresql/data

volumes:
  pg-data: { }

networks:
  mss_hms_network:
    driver: bridge
    ipam:
      driver: default